apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-cicd-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # REPLACE with your GitHub repo URL:
    repoURL: https://github.com/Mohithra-S/kube-flow-pipeline.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true        # Delete resources removed from Git
      selfHeal: true     # Revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
