apiVersion: v1
kind: Service
metadata:
  name: k8s-cicd-app
  namespace: default
  labels:
    app: k8s-cicd-app
spec:
  type: NodePort
  selector:
    app: k8s-cicd-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
